### ISSUE TITLE
Editing Messages

### ISSUE THREAD

**Issue by Sri-SriPod** [ShreyasAyyengar/DepressedBot-Bugs#3]
Usually, when you write a swear word the bot deletes it and dms you with the usual embed. However, when you edit your message with a swear word, the bot deletes it but doesn't dm you.

**Comment by ShreyasAyyengar** [comment]
Thank you for reporting this bug, could you confirm with me that it no longer exists?

**Comment by Sri-SriPod** [comment]
Yes! It works now. :)
